### ISSUE TITLE
Support for type-aware rules

### ISSUE THREAD

**Issue by RebeccaStevens** [antfu/eslint-vitest-rule-tester#4]
### Clear and concise description of the problem

Type-aware rules require type information to run. It would be great if type-aware rules "just worked".

### Suggested solution

Ideally, this should be all that is needed (when using `@typescript-eslint/parser` v8):

```ts
const { valid, invalid } = createRuleTester({
  name,
  rule,
  configs: {
    languageOptions: {
      parser: typescriptParser,
      parserOptions: {
        projectService: true, // or `project: true`
      },
    },
  },
});
```

I don't know what needs to be changed under the hood to make this actually work.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
I don't know what is missing for that to work. Ideally, it should directly work.

I don't use it and don't have the bandwidth to investigate into this, pr welcome, thanks!
